services:
  moodleapp:
    build:
      context: .
      dockerfile: Moodle
    image: moodle-web:1.0
    container_name: moodle-web
    ports:
      - ${MOODLE_PORT:-2080}:80
    volumes:
      - moodledata:/var/www/moodledata
      - moodlefile:/var/www/html
    networks:
      - bridge
      - proxy

volumes:
  moodledata:
  moodlefile:

networks:
  bridge:  
    name: bridge
    external: true
  proxy:
    name: proxy
    external: true