services:
  moodleapp:
    build:
      context: .
      dockerfile: Moodle
    image: moodle-web:1.0
    container_name: moodle-web
    ports:
      - ${MOODLE_PORT:-2080}:80
    volumes:
      - moodledata:/var/www/moodledata
      - moodlefile:/var/www/html
    # networks:
    #   - proxy

volumes:
  moodledata:
  moodlefile:

# networks:
#   proxy:
#     name: proxy
#     external: true