upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 1024M
max_execution_time = 3600
default_charset = "UTF-8"
mbstring.language = UTF-8
mbstring.internal_encoding = UTF-8
max_input_vars = 5000